---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.grafana.storage.grafana }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.grafana.storage.prometheus }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.grafana.storage.loki }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: {{ .Values.grafana.image }}
          env:
            - name: GF_PATHS_DATA
              value: /data/grafana
          ports:
            - containerPort: {{ .Values.grafana.ui.port }}
            - containerPort: {{ .Values.grafana.otlpGrpc.port }}
            - containerPort: {{ .Values.grafana.otlpHttp.port }}
          volumeMounts:
            - name: grafana-data
              mountPath: /data/grafana
            - name: prometheus-data
              mountPath: /data/prometheus
            - name: loki-data
              mountPath: /loki
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-data-pvc
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-data-pvc
        - name: loki-data
          persistentVolumeClaim:
            claimName: loki-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  ports:
    - name: {{ .Values.grafana.ui.name }}
      port: {{ .Values.grafana.ui.port }}
      targetPort: {{ .Values.grafana.ui.port }}
    - name: {{ .Values.grafana.otlpGrpc.name }}
      port: {{ .Values.grafana.otlpGrpc.port }}
      targetPort: {{ .Values.grafana.otlpGrpc.port }}
    - name: {{ .Values.grafana.otlpHttp.name }}
      port: {{ .Values.grafana.otlpHttp.port }}
      targetPort: {{ .Values.grafana.otlpHttp.port }}

