---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.rabbitmq.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-log-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.rabbitmq.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image }}
          command:
            - bash
            - -c
            - "rabbitmq-plugins enable --offline rabbitmq_stomp && rabbitmq-server"
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.rabbitmq.user }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.rabbitmq.password }}
          ports:
            - containerPort: {{ .Values.rabbitmq.amqp.port }}
            - containerPort: {{ .Values.rabbitmq.management.port }}
            - containerPort: {{ .Values.rabbitmq.stomp.port }}
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
            - name: rabbitmq-log
              mountPath: /var/log/rabbitmq
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-data-pvc
        - name: rabbitmq-log
          persistentVolumeClaim:
            claimName: rabbitmq-log-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: {{ .Values.rabbitmq.amqp.name }}
      port: {{ .Values.rabbitmq.amqp.port }}
      targetPort: {{ .Values.rabbitmq.amqp.port }}
    - name: {{ .Values.rabbitmq.management.name }}
      port: {{ .Values.rabbitmq.management.port }}
      targetPort: {{ .Values.rabbitmq.management.port }}
    - name: {{ .Values.rabbitmq.stomp.name }}
      port: {{ .Values.rabbitmq.stomp.port }}
      targetPort: {{ .Values.rabbitmq.stomp.port }}

