apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - name: grafana-ui
      targetPort: 3000
      port: 3000
    - name: otlp-grpc
      targetPort: 4317
      port: 4317
    - name: otlp-http
      targetPort: 4318
      port: 4318
  selector: 
    app: meikocn-lgtm